### ISSUE TITLE
camelCase

### ISSUE THREAD

**Issue by glebfeklistov** [vstirbu/fsm-as-promised#112]
Possible convert callbacks names to camelCase?

**Comment by vstirbu** [comment]
You can already do this:

* configure the callback prefix to be empty:  
```javascript
StateMachine.callbackPrefix = '';
```
* use PascalCase for state names, e.g. `StateName`
* use camelCase for event names, e.g. `eventName`

**Comment by vstirbu** [comment]
Here is an example:

```javascript
StateMachine.callbackPrefix = '';

const fsm = StateMachine({
   init: 'FirstState',
   events: [
      { name: 'someTransition', from: 'FirstState', to: 'SecondState' }
   ],
   callbacks: {
      leaveFirstState: () => {},
      someTransition: () => {},
      enterSecondState: () => {}
   }
});

fsm.someTransition();
```

**Comment by glebfeklistov** [comment]
Thanks

**Comment by glebfeklistov** [comment]
How about standart events "onenter", StateMachine.callbackPrefix = '' not affected on this events, still to lower case use

**Comment by glebfeklistov** [comment]
```js
.then((callbacks.onenter && !pseudoStates[options.to]) ? callbacks.onenter.bind(target,
```
This hardcoded in library

**Comment by vstirbu** [comment]
Oh, right... those need special handling as it might lead to some nasty collisions that could confuse new users.

For example there might be a state machine that has a transition named `leave` which would conflict with the builtin callback `leave`. (this can happen even now)

**Comment by glebfeklistov** [comment]
I'm know. Good like, great solution.
