### ISSUE TITLE
Typescript definition of StateMachineConfiguration

### ISSUE THREAD

**Issue by lantica** [vstirbu/fsm-as-promised#131]
In the mentioned interface, both `initial` and `final` are required.
I think these two option should be optional according to the document / implementation.

**Comment by vstirbu** [comment]
Thanks for reporting this. I'm always defining both `initial` and `final` options, so this was missed.

The `initial` has the default value `none` if not value is provided. I've opened a pull request with a fix. Is this aspect clear now?

**Comment by lantica** [comment]
Yes, thanks for the prompt response
