### ISSUE TITLE
enhancement: support camelCase callback names.

### ISSUE THREAD

**Issue by tech-a-go-go** [vstirbu/fsm-as-promised#69]
Hi there,

Could you please support camel case for the name of callbacks like javascript-state-machine does ?
https://github.com/jakesgordon/javascript-state-machine/blob/e09614a51f2a64724bb151da6462bcb34fdb9883/docs/lifecycle-events.md

Cheers

**Comment by vstirbu** [comment]
Would setting the callback [prefix](https://github.com/vstirbu/fsm-as-promised#configuring-callback-prefix) to an empty string `StateMachine.callbackPrefix = ''` be a solution for you?

**Comment by tech-a-go-go** [comment]
Hi vstirbu,

I will give it a try.

Thanks !
