### ISSUE TITLE
Dangerous Behavior

### ISSUE THREAD

**Issue by tech-a-go-go** [vstirbu/fsm-as-promised#70]
Hi there,

Please take a look at this simple code.

```
const Promise = require('bluebird');
const StateMachine = require('fsm-as-promised');
StateMachine.Promise = Promise;

var fsm = StateMachine({
    initial: 'here',
    events: [
      { name: 'jump', from: 'here', to: 'sky' },
      { name: 'run',  from: 'here', to: 'office' },
    ],
    callbacks: {
      onjump: function (options) {
        return new Promise(function (resolve, reject) {
          resolve(options);
        });
      }
    }
  });

fsm.jump().then((a) => {
  console.log('jump', fsm.current, a);
}).catch((err) => {
  console.log('err jump', err);
});

fsm.run().then((a) => {
  console.log('run', fsm.current, a);
}).catch((err) => {
  console.log('err run', err);
});
```
I thought fsm.jump() will succeed and fsm's state will be sky and fsm.run() will fail because fsm's state has already been changed to sky.

But the result is as follows.
```
jump office { name: 'jump', from: 'here', to: 'sky', args: [] }
run office { name: 'run', from: 'here', to: 'office', args: [] }
```
jump office !? 

jump can only go to the sky...

I know jump() and run() are not connected with a promise chain so while jump() was being processed, run() was executed and run()'s result was taken effect at last.
I believe run() should throw an error or return a promise reject when it's called while other events are being processed..

I think this is very dangerous.

Cheers

**Comment by vstirbu** [comment]
@tech-a-go-go thanks for spotting this behaviour! it was not just dangerous, it was plain faulty...
